export const projects = [
  {
    id: "1",
    icon: "../assets/images/h.png",
    title: "ABC",
    alt: "",
    description: "hdkjfdhfkshkjefhsjkfhksjhjkh",
    github: "",
  },
  {
    id: "2",
    icon: "../assets/images/h.png",
    title: "ABC",
    alt: "",
    description: "hdkjfdhfkshkjefhsjkfhksjhjkh",
    github: "",
  },
  {
    id: "3",
    icon: "../assets/images/h.png",
    title: "ABC",
    alt: "",
    description: "hdkjfdhfkshkjefhsjkfhksjhjkh",
    github: "",
  },
  {
    id: "4",
    icon: "../assets/images/h.png",
    title: "ABC",
    alt: "",
    description: "hdkjfdhfkshkjefhsjkfhksjhjkh",
    github: "",
  },
  {
    id: "5",
    icon: "../assets/images/h.png",
    title: "ABC",
    alt: "",
    description: "hdkjfdhfkshkjefhsjkfhksjhjkh",
    github: "",
  },
  {
    id: "6",
    icon: "../assets/images/h.png",
    title: "ABC",
    alt: "",
    description: "hdkjfdhfkshkjefhsjkfhksjhjkh",
    github: "",
  },
];
