export const projects = [
  {
    id: "1",
    icon: "../assets/projects/logistics.png",
    title: "Online Distribution Logistics System",
    alt: "Logistics",
    description: "Developed tracking operations from dispatch to delivery of items, and created a choice of transport route to distribute the products to the customer using Observer Designer Pattern.",
    github: "https://github.com/divyashree-dal/Logistics",
  },
  {
    id: "2",
    icon: "../assets/projects/database.png",
    title: "Distributed Database Management System",
    alt: "DBMS",
    description: "Developed a fully distributed database management system that maintains Global and Local Data Dictionary, allows different users to log in to the system, and accepts queries as user inputs in standard SQL format.",
    github: "https://github.com/divyashree-dal/DistributedDatabaseManagementSystem",
  },
  {
    id: "3",
    icon: "../assets/projects/dalffins.png",
    title: "Online Tiffins Delivery System",
    alt: "Advanced Web",
    description: "Designed the user profile management system feature, including user registration, user login tasks along with user authentication and user authorization using sessions and JSON Web Tokens.",
    github: "https://github.com/divyashree-dal/Dalffins",
  },
  {
    id: "4",
    icon: "../assets/projects/serverless.png",
    title: "Dal Safe Deposit",
    alt: "Serverless Computing",
    description: "Developed a serverless application for customization of safe deposit using multi-cloud deployment strategy and backend- as-a-service model.",
    github: "https://github.com/divyashree-dal/safedeposit",
  },
  {
    id: "5",
    icon: "../assets/projects/cloud.png",
    title: "An Online Reading System",
    alt: "Advanced topics in Cloud Computing",
    description: "Deployed web application on AWS EC2 and backend on AWS Elastic BeanStalk, and efficiently used Lambda functions, API Gateway, SNS for sending email notifications to the administrator for approvals.",
    github: "https://github.com/divyashree-dal/Dalnewshub",
  },
  {
    id: "6",
    icon: "../assets/projects/analytics.png",
    title: "Absolute Analytics",
    alt: "Absolute Analytics",
    description: "To perform a complete descriptive analysis on the customer dataset to gain information about the subscription plans of a customer. Hence, this information will help us to understand if a customer is churned or not.",
    github: "https://github.com/divyashree-dal/halitel-communications",
  },
];
